Repository bulwark-crypto/Bulwark, pull requests merged in 2018-12, with the labels that each got.

#138 Masternode Tool
  qa/rpc-tests/python-bitcoinrpc/bitcoinrpc/__init__.py
  src/Makefile.qt.include
  src/masternodeconfig.cpp
  src/masternodeconfig.h
  src/qt/configuremasternodepage.cpp
  src/qt/configuremasternodepage.h
  src/qt/forms/configuremasternodepage.ui
  src/qt/forms/masternodelist.ui
  src/qt/forms/outputspage.ui
  src/qt/forms/privkeypage.ui
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/masternodelist.cpp
  src/qt/masternodelist.h
  src/qt/outputspage.cpp
  src/qt/outputspage.h
  src/qt/privkeypage.cpp
  src/qt/privkeypage.h
Labels: QT, enhancement

#142 Update Readme to correctly reflect Reward Splits and supply
  README.md
Labels: documentation

#141 [Qt] Remove Qt4 build support & code fallbacks
  build-aux/m4/bitcoin_qt.m4
  configure.ac
  depends/packages/qt.mk
  src/Makefile.qt.include
  src/clientversion.cpp
  src/qt/addressbookpage.cpp
  src/qt/askpassphrasedialog.cpp
  src/qt/bantablemodel.cpp
  src/qt/bip38tooldialog.cpp
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/blockexplorer.cpp
  src/qt/bulwark.cpp
  src/qt/bulwark.qrc
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/intro.cpp
  src/qt/macdockiconhandler.mm
  src/qt/multisenddialog.cpp
  src/qt/multisigdialog.cpp
  src/qt/obfuscationconfig.cpp
  src/qt/openuridialog.cpp
  src/qt/optionsdialog.cpp
  src/qt/paymentrequestplus.cpp
  src/qt/paymentserver.cpp
  src/qt/peertablemodel.cpp
  src/qt/privacydialog.cpp
  src/qt/receivecoinsdialog.cpp
  src/qt/receiverequestdialog.cpp
  src/qt/res/icons/onion.png
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/sendcoinsentry.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/test/test_main.cpp
  src/qt/transactiondescdialog.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactionrecord.cpp
  src/qt/transactionview.cpp
  src/qt/utilitydialog.cpp
  src/qt/winshutdownmonitor.cpp
  src/qt/winshutdownmonitor.h
  src/qt/zbwkcontroldialog.cpp
Labels: QT, build
